import time

from selenium import webdriver

driver = webdriver.PhantomJS() # or add to your PATH

phrases_to_test = ["Are bigger or small schools better?",
"Are some lives more valuable than others?",
"Are you a very organized person?",
"Are you usually early or late?",
"Countryside or city?",
"Did your family take seasonal vacations?",
"Do you always have to have the latest phone?",
"Do you have any pets? What are their names?",
"Do you like classical music?",
"Do you like documentaries?",
"Do you like horror movies?",
"Fiction or nonfiction books?",
"Physical books or ebooks?",
"Summer or winter sports?",
"Text more or call more? ",
"Do you think that aliens exist?",
"Does fashion help society in any way?",
"Has anyone ever saved your life?",
"Have you ever given to any charities?",
"Have you ever saved someone's life?",
"How ambitious are you?",
"How different was your life one year ago?",
"How do you judge a person?",
"How do you relax after a hard day of work?",
"How do you think you will die?",
"How fast do you read?",
"How have TV shows changed over the years?",
"How have your goals changed over your life?",
"How many apps do you have on your phone?",
"How much do you plan for the future?",
"How often do you binge watch shows?",
"How often do you check your phone?",
"How often do you people watch?",
"How often do you play sports?",
"Is teaching a skill that can be taught?",
"Love or money?",
"What age do you want to live to?",
"What animal is the most majestic?",
"What animal would you most like to eat?",
"What apps have changed your life a lot?",
"What're some things you've had to unlearn?",
"What're the three best apps on your phone?",
"What're three interesting facts about you?",
"What're you absolutely determined to do?",
"What're you addicted to?",
"What're you best at?",
"What're you currently worried about?",
"What're you going to do this weekend?",
"What're you most insecure about?",
"What're you most likely very wrong about?",
"What're your goals for the next two years?",
"What awful movie do you love?",
"What book genres do you like to read?",
"What book has influenced you the most?",
"What book impacted you the most?",
"What brand are you most loyal to?",
"What bridges do you not regret burning?",
"What cartoons did you watch as a child?",
"What city would you most like to live in?",
"What company do you despise?",
"What country is the strangest?",
"What current trend makes no sense to you?",
"What did you do on your last vacation?",
"What did you Google last?",
"What do people think is weird about you?",
"What do you consider to be your best find?",
"What do you do to get rid of stress?",
"What do you fear is hiding in the dark?",
"What do you have doubts about?",
"What do you hope never changes?",
"What do you hope your last words will be?",
"What do you like most about your family?",
"What do you like to do in spring?",
"What do you need help with most often?",
"What do you regret not doing?",
"What do you take for granted?",
"What do you think of buffets?",
"What do you think of homeschooling?",
"What do you think of online education?",
"What do you think of standardized tests?",
"What do you think of tour group packages?",
"What do you want to be remembered for?",
"What do you want your epitaph to be?",
"What do you wish you knew more about?",
"What do you wish you knew more about?",
"What do you wish your phone could do?",
"What does it mean to die well?",
"What escalated very quickly?",
"What fact are your resigned to?",
"What fad or trend do you hope comes back?",
"What food do you crave most often?",
"What food is delicious but a pain to eat?",
"What foods do you absolutely hate?",
"What gets you fired up?",
"What gives your life meaning?",
"What has been blown way out of proportion?",
"What holidays have been over commercialized?",
"What irrational fear do you have?",
"What's a controversial opinion you have?",
"What's a miracle that happens every day?",
"What's one of your favorite smells?",
"What's something you are obsessed with?",
"What's something you will NEVER do again?",
"What's special about the place you grew up?",
"What's the best restaurant in your area?",
"What's the best room in your house? Why?",
"What's the biggest holiday for your family?",
"What's the hardest sport to excel at?",
"What's the longest book you have read?",
"What's the most overrated movie?",
"What's the most useful app on your phone?",
"What's the purpose of a human life?",
"What's the purpose of art in society?",
"What's the silliest fear you have?",
"What's the 'holy grail' of your life?",
"What's your favorite food?",
"What's your favorite holiday?",
"What's your favorite movie soundtrack?",
"What's your guilty pleasure?",
"What job would you be terrible at?",
"What keeps you up at night?",
"What kind of art do you enjoy most?",
"What languages do you wish you could speak?",
"What lie do you tell most often?",
"What makes a good life?",
"What makes you nervous?",
"What movie scene choked you up the most?",
"What movie title best describes your life?",
"What naps are the most satisfying?",
"What near future predictions do you have?",
"What odd smell do you really enjoy?",
"What old trend is coming back these days?",
"What personal goals do you have?",
"What quirks do you have?",
"What really needs to be modernized?",
"What restaurant do you eat at most?",
"What riddles do you know?",
"What risks are worth taking?",
"What shows are you into?",
"What skill would you like to master?",
"What smell brings back great memories?",
"What song always puts you in a good mood?",
"What songs do you only know the chorus to?",
"What songs have you completely memorized?",
"What sports do you like to watch?",
"What takes up too much of your time?",
"What three words best describe you?",
"What trend are you tired of?",
"What values are most important to you?",
"What was ruined because it became popular?",
"What was the darkest movie you've ever seen?",
"What was the last book you read?",
"What was the last funny video you saw?",
"What was the last photo you took?",
"What was the last song you listened to?",
"What was the last song you sung along to?",
"What was your favorite book as a child?",
"What was your most recent lie?",
"What website do you visit most often?",
"What weird or useless talent do you have?",
"What will be the future of TV shows?",
"What will phones be like in 10 years?",
"What will the future of education be?",
"What word do you always mispronounce?",
"What word do you always misspell?",
"What word is a lot of fun to say?",
"What would a perfect city be like?",
"What would be your perfect weekend?",
"What would be your spirit animal?",
"What would you rate 10 / 10?",
"What would your perfect bar look like?",
"What would your perfect room look like?",
"What 'old person' things do you do?",
"What's about to get much better?",
"What's are some of your Pavlovian responses?",
"What's better broken than whole?",
"What's quickly becoming obsolete?",
"What's something that I don't know?",
"What's the best sandwich you've ever had?",
"What's the best show currently on TV?",
"What's the best single day on the calendar?",
"What's the best sitcom past or present?",
"What's the best thing about you?",
"What's the best way to discover new music?",
"What's the best way to start the day?",
"What's the clumsiest thing you've done?",
"What's the coldest you've ever been?",
"What's the craziest video you've ever seen?",
"What's the creepiest tech out there?",
"What's the funniest comedy skit you've seen?",
"What's the funniest joke you know by heart?",
"What's the funniest TV series you have seen?",
"What's the hardest lesson you've learned?",
"What's the hardest you've ever worked?",
"What's the last adventure you went on?",
"What's the most annoying noise?",
"What's the most frustrating product you own?",
"What's the most illegal thing you've done?",
"What's the most immature thing that you do?",
"What's the most pleasant sounding accent?",
"What's the most useful thing you own?",
"What's the oldest thing you own?",
"What's the opposite of a koala?",
"What's the scariest nonhorror movie?",
"What's the spiciest thing you've ever eaten?",
"What's the weirdest crush you've had?",
"What's the worst fast food restaurant?",
"What's the worst hairstyle you've ever had?",
"What's the worst movie trope?",
"What's wrong but sounds right?",
"What's your best story from a wedding?",
"What's your claim to fame?",
"What's your cure for hiccups?",
"What's your dream car?",
"What's your favorite drink?",
"What's your favorite genre of book or movie?",
"What's your favorite genre of movie?",
"What's your favorite holiday movie?",
"What's your favorite number? Why?",
"What's your favorite season? Why?",
"What's your favorite way to waste time?",
"What's your funniest story involving a car?",
"What's your go to casino game?",
"What's your good luck charm?",
"What's your grossest bug story?",
"What's your haunted house story?",
"What's your secret talent?",
"What's your 'and then it got worse' story?",
"What's your 'Back in my day, we...'?",
"When do you feel truly 'alive'?",
"When was the last time you climbed a tree?",
"When was the last time you face palmed?",
"When was the last time you had a food fight?",
"When's censorship warranted?",
"Where are some unusual places you've been?",
"Where are you not welcome anymore?",
"Where do you get your news?",
"Where is the best place to take a date?",
"Where would you like to travel next?",
"Where would you rather be from?",
"Where's the line between soup and cereal?",
"Where's your life headed?",
"Which do you prefer? Books or movies?",
"Which season are you most active in?",
"Which sports do you like to play?",
"Who are some of your favorite athletes?",
"Who are the 3 greatest athletes of all time?",
"Who do you go out of your way to be nice to?",
"Who in your life brings you the most joy?",
"Who in your life has the best / worst luck?",
"Who inspires you to be better?",
"Who is the most creative person you know?",
"Would you like all the questions in a PDF?",
"A gorilla walks into a bar",
"A guy walks into a bar owned by Eminem",
"A man walks into a bar...",
"Ajit Pai.",
"Christmas joke (NSFW)",
"Communism jokes are not funny",
"Dads are like boomerangs.",
"Deaf Sex",
"Do you know how to avoid clickbait?",
"Don't Read If You're A Trump Supporter",
"Girl: 'Come over'",
"Have you seen r/tifu recently.",
"How do you milk sheep?",
"I wish I could be ugly for one day.",
"My boss: You're fired.",
"My favorite joke: Everyone Knows Dave",
"Son: 'Mom, Dad, I'm gay.'",
"The 2016 US Presidential Election",
"The Only Thing Flat-Earthers Fear.....",
"There was this tramp.",
"What do you call a stolen Tesla?",
"Why is Peter Pan always flying?",
"Why will congress never impeach Trump?",
"Hey Daddy, have you seen my sunglasses?",
"'Hey dad why is my sister called Teresa ?'",
"A boy asked his Bitcoin-investing dad...",
"A vegan said to me, 'people who sell meat are gross!'",
"Calm down about the Net Neutrality thing...",
"Did you hear about the Doctor on the United Flight?",
"How do you break up two blind guys fighting?",
"I finally realized my parents favored my twin brother.",
"I found a place where the recycling rate is 98%",
"I hate when people ask how I see myself in 3 years",
"I hope Elon Musk never gets involved in a scandal",
"I refused to believe I was gay and dyslexic.....",
"If you masturbate after smoking marijuana....",
"Jehovah's Witnesses don't celebrate Halloween",
"A man heard that masturbating before sex...",
"Boss wants to have sex with his secretary",
"Hitler, Salin, and EA were having a debate",
"Still my favorite joke I ever made up. :)",
"The husband leans over and asks his wife",
"My wife left me because I'm too insecure.",
"Why will the congress never impeach Trump?",
"What do you call a waffle on a California beach?",
"What do you call an emo a capella group?",
"What is Gordon Ramsay's favorite subreddit?",
"What's the difference between EA and my uncle?",
"Why are people complaining, what EA did was great!",
"Why is EA the worst gaming company in America?",
"So nice to meet you, I found you through...",
"Hey, I found you through...",
"Get Priority Access",
"So nice to meet you, I found you through Michael",
"Craziest thing made out with my grandpa Wbu",
"didnt you fuck my sister?",
"Really? This is how you usually starts a conversation?",
"Tutor me pls",
"Click here to read",
"Quick favor?",
"Um quick question what are the odds of you buying my roommate and I some alcohol",
"What are you currently worried about?",
"What current trend makes no sense to you?",
"What number comes between 1 and 3?",
"What's the best thing about you?",
"Hey, show a girl around town?",
"I'm in town until Friday, wanna grab a bite?",
"Best bar in town?",
"I leave town tomorrow.. dtf?",
"Best club in town?",
"Still in town.. sure you don't want a drink?"]
if __name__ == "__main__":
    high_emv = []
    low_emv = []

    for phrase in phrases_to_test:
        try:
            time.sleep(1)
            driver.get('http://www.aminstitute.com/headline/index.htm')
            original_headline = phrase
            if len(phrase.split()) < 4:
                phrase = phrase +  ' ' + phrase
            headline = phrase
            element = driver.find_element_by_name("text")
            element.send_keys("{}".format(headline))
            element = driver.find_element_by_xpath("//select[@name='category']")
            all_options = element.find_elements_by_tag_name("option")
            for option in all_options:
                print("Value is: %s" % option.get_attribute("value"))
                if 'Education' in option.get_attribute("value"):
                    option.click()
            element = driver.find_element_by_name("Submit2")
            element.click()
            element = driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[1]/table[1]/tbody/tr/td[2]/div/font/b/font")
            print(element[0].text)
            professional = 30
            gifted = 50
            if float(str(element[0].text.strip('%'))) > 45:
                print('Success')
                high_emv.append(original_headline)
            else:
                low_emv.append(original_headline)
        except:
            print("Couldn't establish EMV for given phrase...")

    print('==================== HIGH EMV ====================')
    print(high_emv)
    print('==================== LOW EMV ====================')
    print(low_emv)
